name: Staging Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment"
